version: '3'

services:
  gin:
    build:
      context: .
      dockerfile: docker/gin/Dockerfile
    volumes:
      - .:/go/src/github.com/shunk031/libtorch-gin-api-server
    ports:
      - 5000:5000

  flask:
    build:
      context: .
      dockerfile: docker/flask/Dockerfile
    volumes:
      - .:/go/src/github.com/shunk031/libtorch-gin-api-server
    ports:
      - 5001:5001
